# ╭─────────────────────────Commonly Used ImplementationGuide Properties───────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. The most commonly   │
# │  used properties are included. For a list of all supported properties and their functions,     │
# │  see: https://fshschool.org/docs/sushi/configuration/.                                         │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: hl7.fhir.us.medicaid-provider-credentialing
canonical: http://hl7.org/fhir/us/medicaid-provider-credentialing
name: MedicaidProviderCredentialing
title: Medicaid Provider Credentialing and Enrollment
description: FHIR Implementation Guide for Medicaid Provider Credentialing and Enrollment aligned with MITA and FHIR US Core 6.1.0
status: draft # draft | active | retired | unknown
version: 0.1.0
fhirVersion: 4.0.1 # https://www.hl7.org/fhir/valueset-FHIR-version.html
copyrightYear: 2025+
releaseLabel: ci-build
license: CC0-1.0 # https://www.hl7.org/fhir/valueset-spdx-license.html
jurisdiction: urn:iso:std:iso:3166#US "United States of America" # https://www.hl7.org/fhir/valueset-jurisdiction.html

# The dependencies property corresponds to IG.dependsOn. The key is the
# package id and the value is the version (or dev/current). For advanced
# use cases, the value can be an object with keys for id, uri, and version.
dependencies:
  hl7.fhir.us.core: 6.1.0
  hl7.fhir.us.davinci-pdex-plan-net: 1.1.0

# The pages property corresponds to IG.definition.page. SUSHI can
# auto-generate the page list, but if the author includes pages in
# this file, it is assumed that the author will fully manage the
# pages section and SUSHI will not generate any page entries.
pages:
  index.md:
    title: Home
  mita-overview.md:
    title: MITA Overview
  mita-implementation.md:
    title: MITA Implementation Guidance
  mita-to-fhir-mapping.md:
    title: MITA to FHIR Resource Mapping
  workflow-patterns.md:
    title: Workflow Patterns
  cms-regulations.md:
    title: CMS Regulations
  artifacts.html:
    title: FHIR Artifacts
  profiles.md:
    title: Profiles and Extensions
  search-parameters.md:
    title: Search Parameters
  terminology.md:
    title: Terminology Binding Guidance
  state-customization.md:
    title: State Customization Framework
  data-quality.md:
    title: Data Quality Framework
  security-privacy.md:
    title: Security and Privacy Considerations
  versioning-strategy.md:
    title: Versioning Strategy
  tmsis-mapping.md:
    title: TMSIS to FHIR Mapping
  transition-strategy.md:
    title: Transition Strategy
  testing-framework.md:
    title: Testing Framework
  real-world-implementations.md:
    title: Real-World FHIR Implementation Examples
  implementation-community.md:
    title: Implementation Community and Knowledge Sharing
  feedback-process.md:
    title: Implementation Guide Feedback Process
  examples.md:
    title: Examples
  downloads.md:
    title: Downloads
  roadmap.md:
    title: Implementation Guide Roadmap

# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │ The menu property will be used to generate the input/menu.xml file. The menu is represented    │
# │ as a simple structure where the YAML key is the menu item name and the value is the URL.       │
# │ The IG publisher currently only supports one level deep on sub-menus. To provide a             │
# │ custom menu.xml file, do not include this property and include a `menu.xml` file in            │
# │ input/includes. To use a provided input/includes/menu.xml file, delete the "menu"              │
# │ property below.                                                                                │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  Home: index.html
  Table of Contents: toc.html
  Background:
    MITA Overview: mita-overview.html
    MITA Implementation: mita-implementation.html
    MITA to FHIR Resource Mapping: mita-to-fhir-mapping.html
    Workflow Patterns: workflow-patterns.html
    CMS Regulations: cms-regulations.html
  FHIR Artifacts:
    Profiles: artifacts.html#structures-resource-profiles
    Extensions: artifacts.html#structures-extension-definitions
    Terminology: artifacts.html#terminology-value-sets
  Implementation Guidance:
    Profiles and Extensions: profiles.html
    Search Parameters: search-parameters.html
    Terminology Binding Guidance: terminology.html
    State Customization Framework: state-customization.html
    Data Quality Framework: data-quality.html
    Security & Privacy Considerations: security-privacy.html
    Versioning Strategy: versioning-strategy.html
    TMSIS to FHIR Mapping: tmsis-mapping.html
    Transition Strategy: transition-strategy.html
    Testing Framework: testing-framework.html
    Real World FHIR Implementations: real-world-implementations.html
    Implementation Community: implementation-community.html
    Feedback Process: feedback-process.html
  Examples: examples.html
  Downloads: downloads.html
  Roadmap: roadmap.html

# The parameters property represents IG.definition.parameter. Rather
# than a list of code/value pairs (as in the ImplementationGuide
# resource), the code is the YAML key. If a parameter allows repeating
# values, the value in the YAML should be a sequence/array.
parameters:
  # excludettl: true
  # validation: [allow-any-extensions, no-broken-links]
  # show-inherited-invariants: false
  # usage-stats-opt-out: false
  logging: progress
  # auto-oid-root: 2.16.840.1.113883.4.642.40.42

# Contact information
# contact:
#   - name: HL7 International - Financial Management Work Group
#     telecom:
#       - system: url
#         value: http://www.hl7.org/Special/committees/fm
#       - system: email
#         value: fm@lists.hl7.org

# The global property corresponds to the IG.global property, but it
# uses the type as the YAML key and the profile as its value.
# global:
#   Practitioner: http://hl7.org/fhir/us/medicaid-provider-credentialing/StructureDefinition/medicaid-practitioner
#   PractitionerRole: http://hl7.org/fhir/us/medicaid-provider-credentialing/StructureDefinition/medicaid-practitioner-role
#   Organization: http://hl7.org/fhir/us/medicaid-provider-credentialing/StructureDefinition/medicaid-organization

# Groups can control certain aspects of the IG generation.
# groups:
#   ProviderProfiles:
#     name: Provider Profiles
#     description: Profiles for provider credentialing and enrollment
#     resources:
#     - StructureDefinition/medicaid-practitioner
#     - StructureDefinition/medicaid-practitioner-role
#     - StructureDefinition/medicaid-organization
#     - StructureDefinition/medicaid-healthcare-service
#     - StructureDefinition/medicaid-location
#   CredentialingProfiles:
#     name: Credentialing Profiles
#     description: Profiles for credentialing workflows
#     resources:
#     - StructureDefinition/medicaid-verification-result
#     - StructureDefinition/medicaid-endpoint
#   Extensions:
#     name: Extensions
#     description: Extensions for Medicaid provider credentialing
#     resources:
#     - StructureDefinition/medicaid-provider-id
#     - StructureDefinition/medicaid-enrollment-status
#     - StructureDefinition/medicaid-credentialing-status
#     - StructureDefinition/medicaid-specialty-board-certification
#   ValueSets:
#     name: Value Sets
#     description: Value sets for Medicaid provider credentialing
#     resources:
#     - ValueSet/medicaid-provider-types
#     - ValueSet/medicaid-enrollment-statuses
#     - ValueSet/medicaid-credentialing-statuses
#     - ValueSet/medicaid-specialty-codes

# ╭──────────────────────────────────────────SUSHI flags───────────────────────────────────────────╮
# │  The flags below configure aspects of how SUSHI processes FSH.                                 │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
# FSHOnly: false
# applyExtensionMetadataToRoot: true

# instanceOptions:
#   manualSliceOrdering: true
#   setMetaProfile: always
#   setId: always
